### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by itcuihao** [pure-admin/pure-admin-backend#3]
请问`菜单管理`，`用户管理`，什么时候更新，在网上找了一圈项目，发现该项目最符合眼缘，不过与同类对比之下，缺少菜单与用户的管理页面。希望早日实现。

**Comment by itcuihao** [comment]
> 8月末吧 很忙😂

可以给个表单，表格的例子吗，适合我这种后端选手拿来改改增删改查用的

**Comment by xiaoxian521** [comment]
很多例子啊 具体看 https://github.com/pure-admin/vue-pure-admin
